{% set name = "astrocats" %}
{% set version = "0.3.33" %}
{% set sha256 = "d29c68447ea18b177da432562d39b1882aab2065fae91ed06eee277f87923c96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ads
    - astropy <3.0
    - astroquery
    - beautifulsoup4
    - bokeh
    - future
    - gitdb2
    - gitpython
    - inflect
    - keyring
    - palettable
    - psutil
    - seaborn
    - tqdm
    - tweepy

test:
  imports:
    - astrocats

about:
  home: http://github.com/astrocatalogs/astrocats
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Open astronomy catalogs'

  description: |
    astrocats enables astronomers to construct their own curated catalogs
    of astronomical data with the intention of producing shareable catalogs
    of that data in human-readable formats
  doc_url: https://github.com/astrocatalogs/astrocats
  dev_url: https://github.com/astrocatalogs/astrocats

extra:
  recipe-maintainers:
    - guillochon
    - lzkelley
    - pkgw
