{% set name = "astrocats" %}
{% set version = "0.3.37" %}
{% set sha256 = "fb0dbb16e7d30d4eed7e2e48f36785efe670d129c71560e90856e3c50a9c0ee6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - ads
    - astropy-base
    - beautifulsoup4
    - bokeh
    - future
    - gitpython
    - inflect
    - palettable
    - psutil
    - seaborn
    - setuptools
    - tqdm
  run:
    - python >={{ python_min }}
    - ads
    - astropy-base
    - beautifulsoup4
    - bokeh
    - future
    - gitpython
    - inflect
    - palettable
    - psutil
    - seaborn
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - astrocats

about:
  home: http://github.com/astrocatalogs/astrocats
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Open astronomy catalogs'

  description: |
    astrocats enables astronomers to construct their own curated catalogs
    of astronomical data with the intention of producing shareable catalogs
    of that data in human-readable formats
  doc_url: https://github.com/astrocatalogs/astrocats
  dev_url: https://github.com/astrocatalogs/astrocats

extra:
  recipe-maintainers:
    - guillochon
    - lzkelley
    - pkgw
