travis:
  secure:
    BINSTAR_TOKEN: 0GOg5+vzUtIxqvwLdlJHNJkbszavjXLe65mtEZBcBC2K7ewNMowoTNph/IavMP0xsq62PTP2uUDnH+z1QkYqMeer8gRO+wwX4H5cYddw9UxswpmaG97orOy9dpF4haLuOMQ37MWFFGvc9OxVIJkHseb0HZDIz6RWXnRYaxZrBGMPGA9Lq1Ljvgv6qvKRRDdKFsMA9HPkFd/hTucBiiaTLEwtmxGnGi38YO/y87ALTKIH1tKnHamDaU0q5D2kEoyRYKuP4WtFRe6eG456OvOEznF/2Ynp7CfQLYywHWAhYITm8de/wIf7T+LNXqZkbsK+KV+XyAGBUXHa9aAuZzCTMKcp8EMCMhPhVnaSr2RHjwtihXwjmYAXUKuiGGRUih7pLkivPGTAZEQZjdl7I3Yvm0Z1rDqVWElq7Lbvnom78xG0p4v4V5SJfcczCzHPDxw6oq29PmLu4wxF8tmcLjQdXHjFkg8RYQ8SeDwpPLI4kSzlofadUsKqiQXVAwZlfaIMrArQfVdNyIYfFoxZpnijf4beDACnGLDdsQrGlK0eX4y85kBgEZnfMwWpsnOkMcoe1jftdRKAMxqb8pN3DpstYoD98m+KLGbiLcmjl4cj1a2FrnvtRO+qp8VMDLQjmakH1UHSTkWjgk+YSi6vssdfcrNAo3iUTpDNfERUSuy4aVU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
