travis:
  secure:
    BINSTAR_TOKEN: eFJf2pJ2zCO6CxYycZ9oJiDaH7lO7r8zR8TJIZpSBxAdHPbuTNJva2F3bbMNf16B2OzRc48FpEUO7f5t2GQwJEp58JmA3NcOU/vKwvLr0/FucbW6ZkO+L83BOvPXf4PMconFrfvONR5XSQWuV92+xCexgbdQW6O/XZaziwq8gF1DKeXSAeQRTEdaQgtrw2+//c69TgPIsAPB1A7BqZVsd88ckp6HwOF1MHc+5VPgp/0LmbiqqhuW1PAb69GBlDB6u3Ixg6NFG1BpK+s5iZdWpRKdPDcWFvMTgdl/3cp3a9HWkPXnEeUjxs6NFSGEGL0QsGM1/VdBYdMrtQuzBpSWI2DCZnZiypu6b3ZQSmdkQYWZrGFWApWkLe3NJfPqdhe9zy645ez4iJ9Gg/AsyxOdU+RYvOO82xSR2ZuGthmXmZqHpM97h2oD9hNlcvZVTxGA/KUEPRQwSPlURhQv948FtiQHbQirCrl5UmZfoApvI1J4o0VKfSIKrSKzz66UWfpwmOTa2Qf3L8yt0Es0k/gifdqorJlCj5Wwn1FGP7z99T7uRAA233VPRUk8wcOM7Stl8b3kyb3Gxd8NBw+J0/yDNPREYYRQVNO/cPCidIu4GQcKlcY8TVM3HJccEPf3dGzBVb6nak6bauLdht9ExNrdYWmd0cUdjFxX/DTzP187hS0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
