travis:
  secure:
    BINSTAR_TOKEN: Fuh+l3do8UEYV4Suzmr5Q3TvmyJNYm3xdZeoJM0qzMozObHxgPF2/N5rA2w3ebAJmgrI3woaLre625Xv+pvmkhprkEqjlZIZe8mQ/zeAfwilrpD7B0ZAP9PC4B3Cyikek5KpfYUwvSVG/cMOA41vrTZQPlok6rdoRezo2omlevf8lPf63ujFVkXCoSGl5cyQfOiy107EF5IVv/xwgU0LOVfNl8rDae/UzbRNNJdZyQW4QbAxCiF8OLMeSb19jxczMpcVLcZqHRBJw99en2lQpw5SZWvco9yHGCpcIM+arS47XMjwJgLWJB3xv1xNJjs0HRq1yp+dZNIbfs4tjH6QuRnba4rrdWMG0PSn0ekrXtw01fagVdyLf94pM7OwC9416NYPmp66Oq/RfNIBUicwJrWdar7lFs1i1RuUwA4ad7tC3SiWpcPFBmhhRs5xjUpjza8e9Ulhd6kO+M2s4xTM5kgpsXPiaIBLYW/q0uOxxFrSwt65kXrvvtKP/oVnuy32RhYjyM99WlG68VhL7T8MpgfBJofjshJAyogBX9RUKb3Qmc9LKF654nnO6F20JlPgUBX60JVLVO3+WohjPbg4hWkx6ICJiWOfc0H6mkoh6BvlQTYGWf6FvTIgViSkiuFtz8pZ6FBID/y15MTIFP7kkjAgmwu2ynPM+fVQfUMFh/g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
