travis:
  secure:
    BINSTAR_TOKEN: OXfySIwuFup1Bw/qiVxzpPiVPOko8h3eEF/YLXnmE3AZ8iwZ/bW0JFkOP+yRW1Zd+B+p7Qpg40eYBlKflK7kyMY8r8uSVvTVtpFaosdaKjfLegkYwbZiYRU1wxSw5bwg8eFDIRqTtliT3FZh0EyiIqBS3mlc0Q3KA0gdwOUiyn+yk20DA5SIX26BfpFeIq7K2/pCzah03sLm5YWnJue4+XSD/DykR0TZ3QJ3NXdLg85osQLSouwJP9L683Na0SssDZapGY1Ju0uf5oqoQJx/mhQuzJ0Mr3H7n/fbzedMBlg05jPNj+P3cjLXVtezifI1HRi4799SiqKmsUox1DBC4DTnW9ia/pH04isFhh77tZMZ/WlRul0FOLkBYTNLNlhjG7lvmlPIxSJx6wBUlsQ0gU7ojQImJBrkBUJBpKHYzoHArsDaEI9K00E2Htlfkn3KUqfWWhxxW9oiI4WXFFTvEHYeAATDvlEuh0mUoGLRVDhL0SFXMROOJt47gQnIHNJA740LS/JJMF6eM7lwmqefXUKzkFYMkDCDDT56tvoUR1EMR8QnxEf8IVD0cSLQqZeOsdkxb4rnsfLI1+1jzvO4DPNIJdLPix1M8eF6Tc+Zd4UmO/v3+f+FfXR/EMMmTJpX8+Cc6m0N+2qsd5UOM4cuNlHP3aGbMDmXlKxeZ1Lyx2E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
