travis:
  secure:
    BINSTAR_TOKEN: Qt62e6TvRiTNPbL2Gve3rXjIkYEKuo4yx7YhqDKLc1z49Hl4uY/SsJoJ9jOXo3w7zZl2dOiHbm4ibv+n28ux0xHYQzpm9ygWaOV7SAl09CAeB6PTrzE8idOMG2/JslWt3FG/vQB9i3FiYFhCqbBBSwAUmFlNqJBaFDeIOF1rEL3bJbxE458UNjfkfSzcohgRGyfBBxvsi1DnjIO4AWwTfIYSmu3wnytOyLmxoJHeiv2HJLoKkoO2jtNMNwoYTSuNntV9IME4t139llgrDRtABAd5amP6V54KUlzwAjVOyL1jadjEwa8ky0ChnI6DhDlwL9uUm7nVCEKQvc7o1wSfSj1I7gTwqNTU+1hCv78LqY5uUkaeTA+lEfuixrbvqfaifEDJpKV6AEobBeOjqVs21G+ZMs2cHDLbiLEXakTIuPa+cgLrThJVIVyN7HTQlj4e0ckiXj6IW4M8GxU8JHEmQoaxZscEXFFWOcUDUQ3yDGFUwXTtBY0aGAY1rnGOwdA0hwNNhdBAwlX+PCoZ4O8fh/FX+t4fcvq5bTZokapUgESgeLNw8qFdVSBNhoSAjxhEk7b4ee9KpQWmXmOXS9/1Cxqx3ThHibHWEenMurkhxPdhzeExWPCbXIbDA1vmLN//XbR4Uef7Kxx42VyWOm/xuQvkyVDw0MpvrlaGZ6mw7FM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
